# service for apibrew server
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-apibrew-server"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.name }}-apibrew-server"
spec:
  type: NodePort
  ports:
    - port: 9009
      targetPort: 9009
      protocol: TCP
      name: http
  selector:
    app: "{{ .Values.name }}-apibrew-server"