# service for apibrew server
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: LoadBalancer
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
    - port: 9443
      targetPort: 9443
      protocol: TCP
      name: grpcs
  selector:
    app: gateway