// AUTOGENERATED FILE

//go:build !codeanalysis

package model

import "github.com/google/uuid"
import "time"

type FunctionExecutionEngine struct {
	Id          *uuid.UUID        `json:"id,omitempty"`
	Name        string            `json:"name,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
	CreatedBy   *string           `json:"createdBy,omitempty"`
	UpdatedBy   *string           `json:"updatedBy,omitempty"`
	CreatedOn   *time.Time        `json:"createdOn,omitempty"`
	UpdatedOn   *time.Time        `json:"updatedOn,omitempty"`
	Version     int32             `json:"version,omitempty"`
}

func (s *FunctionExecutionEngine) GetId() *uuid.UUID {
	return s.Id
}
func (s *FunctionExecutionEngine) GetName() string {
	return s.Name
}
func (s *FunctionExecutionEngine) GetAnnotations() map[string]string {
	return s.Annotations
}
func (s *FunctionExecutionEngine) GetCreatedBy() *string {
	return s.CreatedBy
}
func (s *FunctionExecutionEngine) GetUpdatedBy() *string {
	return s.UpdatedBy
}
func (s *FunctionExecutionEngine) GetCreatedOn() *time.Time {
	return s.CreatedOn
}
func (s *FunctionExecutionEngine) GetUpdatedOn() *time.Time {
	return s.UpdatedOn
}
func (s *FunctionExecutionEngine) GetVersion() int32 {
	return s.Version
}
