// Code generated by apbr generate. DO NOT EDIT.
// versions:
// 	apbr generate v1.2

//go:build !codeanalysis

package model

import "github.com/google/uuid"
import "time"

type Function struct {
	Id            *uuid.UUID            `json:"id,omitempty"`
	Annotations   map[string]string     `json:"annotations,omitempty"`
	Name          string                `json:"name,omitempty"`
	Language      FunctionLanguage      `json:"language,omitempty"`
	Source        string                `json:"source,omitempty"`
	ContentFormat FunctionContentFormat `json:"contentFormat,omitempty"`
	Version       int32                 `json:"version,omitempty"`
	AuditData     *FunctionAuditData    `json:"auditData,omitempty"`
}

func (s Function) GetId() *uuid.UUID {
	return s.Id
}
func (s Function) GetAnnotations() map[string]string {
	return s.Annotations
}
func (s Function) GetName() string {
	return s.Name
}
func (s Function) GetLanguage() FunctionLanguage {
	return s.Language
}
func (s Function) GetSource() string {
	return s.Source
}
func (s Function) GetContentFormat() FunctionContentFormat {
	return s.ContentFormat
}
func (s Function) GetVersion() int32 {
	return s.Version
}
func (s Function) GetAuditData() *FunctionAuditData {
	return s.AuditData
}

type FunctionAuditData struct {
	CreatedBy *string    `json:"createdBy,omitempty"`
	UpdatedBy *string    `json:"updatedBy,omitempty"`
	CreatedOn *time.Time `json:"createdOn,omitempty"`
	UpdatedOn *time.Time `json:"updatedOn,omitempty"`
}

func (s FunctionAuditData) GetCreatedBy() *string {
	return s.CreatedBy
}
func (s FunctionAuditData) GetUpdatedBy() *string {
	return s.UpdatedBy
}
func (s FunctionAuditData) GetCreatedOn() *time.Time {
	return s.CreatedOn
}
func (s FunctionAuditData) GetUpdatedOn() *time.Time {
	return s.UpdatedOn
}

type FunctionLanguage string

const (
	FunctionLanguage_JAVASCRIPT FunctionLanguage = "JAVASCRIPT"
	FunctionLanguage_TYPESCRIPT FunctionLanguage = "TYPESCRIPT"
)

type FunctionContentFormat string

const (
	FunctionContentFormat_TEXT  FunctionContentFormat = "TEXT"
	FunctionContentFormat_TAR   FunctionContentFormat = "TAR"
	FunctionContentFormat_TARGZ FunctionContentFormat = "TAR_GZ"
)
