// AUTOGENERATED FILE

//go:build !codeanalysis

package model

import "github.com/google/uuid"
import "time"

type Module struct {
	Id          *uuid.UUID               `json:"id,omitempty"`
	Package     string                   `json:"package,omitempty"`
	Content     []uint8                  `json:"content,omitempty"`
	Engine      *FunctionExecutionEngine `json:"engine,omitempty"`
	Annotations map[string]string        `json:"annotations,omitempty"`
	CreatedBy   *string                  `json:"createdBy,omitempty"`
	UpdatedBy   *string                  `json:"updatedBy,omitempty"`
	CreatedOn   *time.Time               `json:"createdOn,omitempty"`
	UpdatedOn   *time.Time               `json:"updatedOn,omitempty"`
	Version     int32                    `json:"version,omitempty"`
}

func (s *Module) GetId() *uuid.UUID {
	return s.Id
}
func (s *Module) GetPackage() string {
	return s.Package
}
func (s *Module) GetContent() []uint8 {
	return s.Content
}
func (s *Module) GetEngine() *FunctionExecutionEngine {
	return s.Engine
}
func (s *Module) GetAnnotations() map[string]string {
	return s.Annotations
}
func (s *Module) GetCreatedBy() *string {
	return s.CreatedBy
}
func (s *Module) GetUpdatedBy() *string {
	return s.UpdatedBy
}
func (s *Module) GetCreatedOn() *time.Time {
	return s.CreatedOn
}
func (s *Module) GetUpdatedOn() *time.Time {
	return s.UpdatedOn
}
func (s *Module) GetVersion() int32 {
	return s.Version
}
