// AUTOGENERATED FILE

//go:build !codeanalysis

package model

import "github.com/google/uuid"
import "time"

type Schedule struct {
	Id          *uuid.UUID        `json:"id,omitempty"`
	Name        string            `json:"name,omitempty"`
	Schedule    string            `json:"schedule,omitempty"`
	Function    *Function         `json:"function,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
	CreatedBy   *string           `json:"createdBy,omitempty"`
	UpdatedBy   *string           `json:"updatedBy,omitempty"`
	CreatedOn   *time.Time        `json:"createdOn,omitempty"`
	UpdatedOn   *time.Time        `json:"updatedOn,omitempty"`
	Version     int32             `json:"version,omitempty"`
}

func (s *Schedule) GetId() *uuid.UUID {
	return s.Id
}
func (s *Schedule) GetName() string {
	return s.Name
}
func (s *Schedule) GetSchedule() string {
	return s.Schedule
}
func (s *Schedule) GetFunction() *Function {
	return s.Function
}
func (s *Schedule) GetAnnotations() map[string]string {
	return s.Annotations
}
func (s *Schedule) GetCreatedBy() *string {
	return s.CreatedBy
}
func (s *Schedule) GetUpdatedBy() *string {
	return s.UpdatedBy
}
func (s *Schedule) GetCreatedOn() *time.Time {
	return s.CreatedOn
}
func (s *Schedule) GetUpdatedOn() *time.Time {
	return s.UpdatedOn
}
func (s *Schedule) GetVersion() int32 {
	return s.Version
}
